# Generated by Django 4.2.7 on 2023-11-13 02:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_category_listing_comment_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="listing_images/"),
        ),
    ]
