# Generated by Django 4.2.7 on 2023-11-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
