# Generated by Django 4.2.7 on 2023-11-14 03:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0006_remove_listing_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="watchlist",
            name="listings",
            field=models.ManyToManyField(to="auctions.listing"),
        ),
    ]
