# Generated by Django 4.2.7 on 2023-11-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0007_watchlist_listings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name="listing",
            name="description",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="listing",
            name="title",
            field=models.CharField(max_length=25),
        ),
    ]
