# Generated by Django 4.2.7 on 2023-11-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_comment_content_alter_listing_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='is_winning',
            field=models.BooleanField(default=False),
        ),
    ]
